---
name: POE-Component-Jabber
version: 1.21
author: []
abstract: A POE Component for communicating over Jabber
license: gpl
resources:
  license: http://www.opensource.org/licenses/gpl-license.php
requires:
  Authen::SASL: 2.10
  Digest::SHA1: 2.11
  Filter::Template: 1.01
  MIME::Base64: 3.07
  POE: 0.34_01
  POE::Component::SSLify: 0.04
  POE::Filter::XML: 0.29
  perl: 5.8.1
provides:
  POE::Component::Jabber:
    file: lib/POE/Component/Jabber.pm
    version: 1.21
  POE::Component::Jabber::Client::Component:
    file: lib/POE/Component/Jabber/Client/Component.pm
    version: 1.21
  POE::Component::Jabber::Client::J2:
    file: lib/POE/Component/Jabber/Client/J2.pm
    version: 1.21
  POE::Component::Jabber::Client::Legacy:
    file: lib/POE/Component/Jabber/Client/Legacy.pm
    version: 1.21
  POE::Component::Jabber::Client::XMPP:
    file: lib/POE/Component/Jabber/Client/XMPP.pm
    version: 1.21
  POE::Component::Jabber::Error:
    file: lib/POE/Component/Jabber/Error.pm
    version: 1.21
  POE::Component::Jabber::Server:
    file: lib/POE/Component/Jabber/Server.pm
    version: 1.21
  POE::Component::Jabber::Server::InputHandler:
    file: lib/POE/Component/Jabber/Server/InputHandler.pm
  POE::Component::Jabber::Server::PresenceManager:
    file: lib/POE/Component/Jabber/Server/PresenceManager.pm
  POE::Component::Jabber::Server::RosterTable:
    file: lib/POE/Component/Jabber/Server/RosterTable.pm
  POE::Component::Jabber::Server::RouteProcessor:
    file: lib/POE/Component/Jabber/Server/RouteProcessor.pm
  POE::Component::Jabber::Server::RouteTable:
    file: lib/POE/Component/Jabber/Server/RouteTable.pm
  POE::Component::Jabber::Server::SelfRouter:
    file: lib/POE/Component/Jabber/Server/SelfRouter.pm
  POE::Component::Jabber::Server::Socket:
    file: lib/POE/Component/Jabber/Server/Socket.pm
    version: 1.21
  POE::Component::Jabber::Server::SocketServer:
    file: lib/POE/Component/Jabber/Server/SocketServer.pm
generated_by: Module::Build version 0.28
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
